frame_id: sonar
frequency_mode: 2
gain_assist: false
gain_percent: 70.0
gamma_correction: 153
nbeams: 1
ping_rate: 2
qos_overrides./parameter_events.publisher.depth: 1000
qos_overrides./parameter_events.publisher.durability: volatile
qos_overrides./parameter_events.publisher.history: keep_last
qos_overrides./parameter_events.publisher.reliability: reliable
range: 20.0
run: false
salinity: 0.0
sound_speed: 1482.8131205259756
temperature_stop: 35.0
temperature_warn: 30.0
use_salinity: false
use_sim_time: false
